[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Clean, standard remappings that now work because of the symlink
remappings = [
    "@ccip/=lib/ccip/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
# f this remapping
