[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia = "https://eth-sepolia.g.alchemy.com/v2/Ui4FxkxcZJxNj2-xE9xHZ", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/Ui4FxkxcZJxNj2-xE9xHZ" } 

auto_detect_remappings = false

remappings = [
    "@chainlink/contracts/src/v0.8/shared/=lib/chainlink-evm/contracts/src/v0.8/shared/",
    "@chainlink/contracts-ccip/=lib/chainlink-ccip/chains/evm/",
    "@chainlink/contracts/src/v0.8/vendor/openzeppelin-solidity/v4.8.3/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/src/v0.8/vendor/openzeppelin-solidity/v5.0.2/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-evm/contracts/",
    "@chainlink-ccip/=lib/chainlink-ccip/chains/evm/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@forge/=lib/forge-std/src/",
    "@chainlink-local/=lib/chainlink-local/"
]