[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia = "https://eth-sepolia.g.alchemy.com/v2/Ui4FxkxcZJxNj2-xE9xHZ", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/Ui4FxkxcZJxNj2-xE9xHZ" } 

# Clean, standard remappings that now work because of the symlink
remappings = [
    "@chainlink-ccip/=lib/chainlink-ccip/chains/evm/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink-local/=lib/chainlink-local/",
    "@forge/=lib/forge-std/src/"
]
